### ISSUE TITLE
Possible video sync bug?

### ISSUE THREAD

**Issue by LVNeptune** [borti4938/n64rgb_fw4viletim#1]
Flashed v2 onto the v2 Tim board and whenever deblur is enabled it seems to work fine but if the heuristic turns deblur off or I manually turn it off the video goes out of sync. My PVM will not recognize a signal at all and my CRT recognizes a signal in black and white and scrolling like it's out of sync. On Tim's firmware, deblur is disabled by default and video still looks fine. Any ideas?

**Comment by borti4938** [comment]
fixed
